project:
  type: website

website:
  title: "Virgílio Mendes"
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/Mendes_txt
      - icon: github
        href: https://github.com/virgiliomendes
      - icon: linkedin
        href: https://www.linkedin.com/in/virgiliomendes/
      - icon: mailbox
        href: virgilioebm@gmail.com
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects
      - text: CV
        href: https://github.com/virgiliomendes/virgiliomendes/blob/master/CV_Virgilio_mercado.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



